# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\hack\eclipse\ergotime\client\main_win.ui'
#
# Created by: PyQt5 UI code generator 5.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Main(object):
    def setupUi(self, Main):
        Main.setObjectName("Main")
        Main.resize(822, 677)
        self.centralwidget = QtWidgets.QWidget(Main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter_1 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_1.setOrientation(QtCore.Qt.Vertical)
        self.splitter_1.setObjectName("splitter_1")
        self.horizontalGroupBox_2 = QtWidgets.QGroupBox(self.splitter_1)
        self.horizontalGroupBox_2.setObjectName("horizontalGroupBox_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.horizontalGroupBox_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.splitter = QtWidgets.QSplitter(self.horizontalGroupBox_2)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.splitter)
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.comboCurrentActivity = QtWidgets.QComboBox(self.horizontalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboCurrentActivity.sizePolicy().hasHeightForWidth())
        self.comboCurrentActivity.setSizePolicy(sizePolicy)
        self.comboCurrentActivity.setObjectName("comboCurrentActivity")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboCurrentActivity)
        self.label_11 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.comboCurrentProject = QtWidgets.QComboBox(self.horizontalLayoutWidget_4)
        self.comboCurrentProject.setObjectName("comboCurrentProject")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboCurrentProject)
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.dtCurrentStart = QtWidgets.QDateTimeEdit(self.horizontalLayoutWidget_4)
        self.dtCurrentStart.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.dtCurrentStart.setCurrentSection(QtWidgets.QDateTimeEdit.YearSection)
        self.dtCurrentStart.setCalendarPopup(False)
        self.dtCurrentStart.setObjectName("dtCurrentStart")
        self.horizontalLayout_13.addWidget(self.dtCurrentStart)
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_13.addWidget(self.label_5)
        self.timeCurrentLen = QtWidgets.QTimeEdit(self.horizontalLayoutWidget_4)
        self.timeCurrentLen.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.timeCurrentLen.setReadOnly(True)
        self.timeCurrentLen.setCurrentSection(QtWidgets.QDateTimeEdit.HourSection)
        self.timeCurrentLen.setObjectName("timeCurrentLen")
        self.horizontalLayout_13.addWidget(self.timeCurrentLen)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_13)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.btnCurrentStart = QtWidgets.QToolButton(self.horizontalLayoutWidget_4)
        self.btnCurrentStart.setObjectName("btnCurrentStart")
        self.horizontalLayout_2.addWidget(self.btnCurrentStart)
        self.btnCurrentStop = QtWidgets.QToolButton(self.horizontalLayoutWidget_4)
        self.btnCurrentStop.setObjectName("btnCurrentStop")
        self.horizontalLayout_2.addWidget(self.btnCurrentStop)
        self.formLayout.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.horizontalLayout_7.addLayout(self.formLayout)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.splitter)
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.horizontalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_10.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_10.setSpacing(3)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.txtCurrentComment = QtWidgets.QTextEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtCurrentComment.sizePolicy().hasHeightForWidth())
        self.txtCurrentComment.setSizePolicy(sizePolicy)
        self.txtCurrentComment.setAcceptRichText(False)
        self.txtCurrentComment.setObjectName("txtCurrentComment")
        self.horizontalLayout_10.addWidget(self.txtCurrentComment)
        self.horizontalLayout.addWidget(self.groupBox)
        self.verticalLayout_6.addWidget(self.splitter)
        self.groupBox_2 = QtWidgets.QGroupBox(self.splitter_1)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btnReportSync = QtWidgets.QToolButton(self.groupBox_2)
        self.btnReportSync.setObjectName("btnReportSync")
        self.horizontalLayout_4.addWidget(self.btnReportSync)
        self.chkReportSyncAuto = QtWidgets.QCheckBox(self.groupBox_2)
        self.chkReportSyncAuto.setObjectName("chkReportSyncAuto")
        self.horizontalLayout_4.addWidget(self.chkReportSyncAuto)
        self.btnSetSelectedDatePrev = QtWidgets.QToolButton(self.groupBox_2)
        self.btnSetSelectedDatePrev.setObjectName("btnSetSelectedDatePrev")
        self.horizontalLayout_4.addWidget(self.btnSetSelectedDatePrev)
        self.btnSetSelectedDateToday = QtWidgets.QToolButton(self.groupBox_2)
        self.btnSetSelectedDateToday.setObjectName("btnSetSelectedDateToday")
        self.horizontalLayout_4.addWidget(self.btnSetSelectedDateToday)
        self.btnSetSelectedDateNext = QtWidgets.QToolButton(self.groupBox_2)
        self.btnSetSelectedDateNext.setObjectName("btnSetSelectedDateNext")
        self.horizontalLayout_4.addWidget(self.btnSetSelectedDateNext)
        self.selectedDate = QtWidgets.QDateEdit(self.groupBox_2)
        self.selectedDate.setTime(QtCore.QTime(1, 0, 0))
        self.selectedDate.setCurrentSection(QtWidgets.QDateTimeEdit.DaySection)
        self.selectedDate.setCalendarPopup(True)
        self.selectedDate.setObjectName("selectedDate")
        self.horizontalLayout_4.addWidget(self.selectedDate)
        self.reportsWeekday = QtWidgets.QLabel(self.groupBox_2)
        self.reportsWeekday.setObjectName("reportsWeekday")
        self.horizontalLayout_4.addWidget(self.reportsWeekday)
        self.btn_report_create = QtWidgets.QToolButton(self.groupBox_2)
        self.btn_report_create.setObjectName("btn_report_create")
        self.horizontalLayout_4.addWidget(self.btn_report_create)
        self.btn_report_edit = QtWidgets.QToolButton(self.groupBox_2)
        self.btn_report_edit.setObjectName("btn_report_edit")
        self.horizontalLayout_4.addWidget(self.btn_report_edit)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.line = QtWidgets.QFrame(self.groupBox_2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.tableReports = QtWidgets.QTableWidget(self.groupBox_2)
        self.tableReports.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableReports.setAutoScroll(False)
        self.tableReports.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableReports.setAlternatingRowColors(False)
        self.tableReports.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableReports.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableReports.setObjectName("tableReports")
        self.tableReports.setColumnCount(0)
        self.tableReports.setRowCount(0)
        self.tableReports.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_2.addWidget(self.tableReports)
        self.groupHistory = QtWidgets.QGroupBox(self.splitter_1)
        self.groupHistory.setObjectName("groupHistory")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupHistory)
        self.verticalLayout_5.setContentsMargins(6, 3, 6, 3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.txtLog = QtWidgets.QPlainTextEdit(self.groupHistory)
        self.txtLog.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.txtLog.setReadOnly(True)
        self.txtLog.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.txtLog.setMaximumBlockCount(5000)
        self.txtLog.setObjectName("txtLog")
        self.verticalLayout_5.addWidget(self.txtLog)
        self.verticalLayout.addWidget(self.splitter_1)
        Main.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Main)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 822, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuActivity = QtWidgets.QMenu(self.menubar)
        self.menuActivity.setObjectName("menuActivity")
        self.menuReport = QtWidgets.QMenu(self.menubar)
        self.menuReport.setObjectName("menuReport")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        Main.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Main)
        self.statusbar.setObjectName("statusbar")
        Main.setStatusBar(self.statusbar)
        self.actionAbout = QtWidgets.QAction(Main)
        self.actionAbout.setObjectName("actionAbout")
        self.actionSettings = QtWidgets.QAction(Main)
        self.actionSettings.setObjectName("actionSettings")
        self.actionShortlist = QtWidgets.QAction(Main)
        self.actionShortlist.setObjectName("actionShortlist")
        self.actionActivitySync = QtWidgets.QAction(Main)
        self.actionActivitySync.setObjectName("actionActivitySync")
        self.actionReportSync = QtWidgets.QAction(Main)
        self.actionReportSync.setObjectName("actionReportSync")
        self.actionNew = QtWidgets.QAction(Main)
        self.actionNew.setObjectName("actionNew")
        self.actionServer_web_page = QtWidgets.QAction(Main)
        self.actionServer_web_page.setObjectName("actionServer_web_page")
        self.actionDocumentation = QtWidgets.QAction(Main)
        self.actionDocumentation.setObjectName("actionDocumentation")
        self.actionExit = QtWidgets.QAction(Main)
        self.actionExit.setObjectName("actionExit")
        self.actionSave_windows_position = QtWidgets.QAction(Main)
        self.actionSave_windows_position.setObjectName("actionSave_windows_position")
        self.actionLoad_windows_position = QtWidgets.QAction(Main)
        self.actionLoad_windows_position.setObjectName("actionLoad_windows_position")
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionSettings)
        self.menuEdit.addAction(self.actionShortlist)
        self.menuEdit.addAction(self.actionSave_windows_position)
        self.menuActivity.addAction(self.actionActivitySync)
        self.menuReport.addAction(self.actionReportSync)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuActivity.menuAction())
        self.menubar.addAction(self.menuReport.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(Main)
        QtCore.QMetaObject.connectSlotsByName(Main)
        Main.setTabOrder(self.comboCurrentActivity, self.txtCurrentComment)
        Main.setTabOrder(self.txtCurrentComment, self.btnReportSync)
        Main.setTabOrder(self.btnReportSync, self.chkReportSyncAuto)
        Main.setTabOrder(self.chkReportSyncAuto, self.btnSetSelectedDatePrev)
        Main.setTabOrder(self.btnSetSelectedDatePrev, self.btnSetSelectedDateToday)
        Main.setTabOrder(self.btnSetSelectedDateToday, self.btnSetSelectedDateNext)
        Main.setTabOrder(self.btnSetSelectedDateNext, self.selectedDate)
        Main.setTabOrder(self.selectedDate, self.tableReports)
        Main.setTabOrder(self.tableReports, self.txtLog)

    def retranslateUi(self, Main):
        _translate = QtCore.QCoreApplication.translate
        Main.setWindowTitle(_translate("Main", "ErgoTime"))
        self.horizontalGroupBox_2.setTitle(_translate("Main", "Current Report"))
        self.label_3.setText(_translate("Main", "Activity"))
        self.label_11.setText(_translate("Main", "Project"))
        self.label_4.setText(_translate("Main", "Start"))
        self.dtCurrentStart.setDisplayFormat(_translate("Main", "yyyy-MM-dd HH:mm"))
        self.label_5.setText(_translate("Main", "Length"))
        self.timeCurrentLen.setDisplayFormat(_translate("Main", "HH:mm:ss"))
        self.btnCurrentStart.setText(_translate("Main", "Start"))
        self.btnCurrentStop.setText(_translate("Main", "Stop"))
        self.groupBox.setTitle(_translate("Main", "Comment"))
        self.groupBox_2.setTitle(_translate("Main", "Reports"))
        self.btnReportSync.setText(_translate("Main", "Sync"))
        self.chkReportSyncAuto.setText(_translate("Main", "Auto"))
        self.btnSetSelectedDatePrev.setText(_translate("Main", "<"))
        self.btnSetSelectedDateToday.setText(_translate("Main", "Today"))
        self.btnSetSelectedDateNext.setText(_translate("Main", ">"))
        self.reportsWeekday.setText(_translate("Main", "<weekday>"))
        self.btn_report_create.setText(_translate("Main", "Create"))
        self.btn_report_edit.setText(_translate("Main", "Edit"))
        self.groupHistory.setTitle(_translate("Main", "History"))
        self.menuFile.setTitle(_translate("Main", "File"))
        self.menuEdit.setTitle(_translate("Main", "Edit"))
        self.menuActivity.setTitle(_translate("Main", "Activity"))
        self.menuReport.setTitle(_translate("Main", "Report"))
        self.menuHelp.setTitle(_translate("Main", "Help"))
        self.actionAbout.setText(_translate("Main", "About"))
        self.actionSettings.setText(_translate("Main", "Settings"))
        self.actionShortlist.setText(_translate("Main", "Shortlist"))
        self.actionActivitySync.setText(_translate("Main", "Sync"))
        self.actionReportSync.setText(_translate("Main", "Sync"))
        self.actionNew.setText(_translate("Main", "New"))
        self.actionServer_web_page.setText(_translate("Main", "Server web page"))
        self.actionDocumentation.setText(_translate("Main", "Documentation"))
        self.actionExit.setText(_translate("Main", "Exit"))
        self.actionSave_windows_position.setText(_translate("Main", "Save windows position"))
        self.actionLoad_windows_position.setText(_translate("Main", "Load windows position"))

