# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\hack\git\ergotime\client\main_win.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Main(object):
    def setupUi(self, Main):
        Main.setObjectName("Main")
        Main.resize(807, 624)
        self.centralwidget = QtWidgets.QWidget(Main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalGroupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.horizontalGroupBox_2.setObjectName("horizontalGroupBox_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalGroupBox_2)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.comboCurrentActivity = QtWidgets.QComboBox(self.horizontalGroupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboCurrentActivity.sizePolicy().hasHeightForWidth())
        self.comboCurrentActivity.setSizePolicy(sizePolicy)
        self.comboCurrentActivity.setObjectName("comboCurrentActivity")
        self.gridLayout_3.addWidget(self.comboCurrentActivity, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.horizontalGroupBox_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.horizontalGroupBox_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 3, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.horizontalGroupBox_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 2, 0, 1, 1)
        self.dtCurrentStart = QtWidgets.QDateTimeEdit(self.horizontalGroupBox_2)
        self.dtCurrentStart.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dtCurrentStart.setCurrentSection(QtWidgets.QDateTimeEdit.YearSection)
        self.dtCurrentStart.setCalendarPopup(False)
        self.dtCurrentStart.setObjectName("dtCurrentStart")
        self.gridLayout_3.addWidget(self.dtCurrentStart, 2, 1, 1, 1)
        self.timeCurrentLen = QtWidgets.QTimeEdit(self.horizontalGroupBox_2)
        self.timeCurrentLen.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.timeCurrentLen.setCurrentSection(QtWidgets.QDateTimeEdit.HourSection)
        self.timeCurrentLen.setObjectName("timeCurrentLen")
        self.gridLayout_3.addWidget(self.timeCurrentLen, 3, 1, 1, 1)
        self.btnCurrentStart = QtWidgets.QToolButton(self.horizontalGroupBox_2)
        self.btnCurrentStart.setObjectName("btnCurrentStart")
        self.gridLayout_3.addWidget(self.btnCurrentStart, 0, 3, 1, 1)
        self.btnCurrentStop = QtWidgets.QToolButton(self.horizontalGroupBox_2)
        self.btnCurrentStop.setObjectName("btnCurrentStop")
        self.gridLayout_3.addWidget(self.btnCurrentStop, 2, 3, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.horizontalGroupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_10.setSpacing(3)
        self.horizontalLayout_10.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.txtCurrentComment = QtWidgets.QTextEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtCurrentComment.sizePolicy().hasHeightForWidth())
        self.txtCurrentComment.setSizePolicy(sizePolicy)
        self.txtCurrentComment.setAcceptRichText(False)
        self.txtCurrentComment.setObjectName("txtCurrentComment")
        self.horizontalLayout_10.addWidget(self.txtCurrentComment)
        self.gridLayout_3.addWidget(self.groupBox, 0, 2, 4, 1)
        self.label_11 = QtWidgets.QLabel(self.horizontalGroupBox_2)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 1, 0, 1, 1)
        self.comboCurrentProject = QtWidgets.QComboBox(self.horizontalGroupBox_2)
        self.comboCurrentProject.setObjectName("comboCurrentProject")
        self.gridLayout_3.addWidget(self.comboCurrentProject, 1, 1, 1, 1)
        self.horizontalLayout_7.addLayout(self.gridLayout_3)
        self.verticalLayout.addWidget(self.horizontalGroupBox_2)
        self.splitter_2 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.splitter_1 = QtWidgets.QSplitter(self.splitter_2)
        self.splitter_1.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_1.setObjectName("splitter_1")
        self.groupBox_2 = QtWidgets.QGroupBox(self.splitter_1)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btnReportSync = QtWidgets.QToolButton(self.groupBox_2)
        self.btnReportSync.setObjectName("btnReportSync")
        self.horizontalLayout_4.addWidget(self.btnReportSync)
        self.chkReportSyncAuto = QtWidgets.QCheckBox(self.groupBox_2)
        self.chkReportSyncAuto.setObjectName("chkReportSyncAuto")
        self.horizontalLayout_4.addWidget(self.chkReportSyncAuto)
        self.btnSetSelectedDatePrev = QtWidgets.QToolButton(self.groupBox_2)
        self.btnSetSelectedDatePrev.setObjectName("btnSetSelectedDatePrev")
        self.horizontalLayout_4.addWidget(self.btnSetSelectedDatePrev)
        self.btnSetSelectedDateToday = QtWidgets.QToolButton(self.groupBox_2)
        self.btnSetSelectedDateToday.setObjectName("btnSetSelectedDateToday")
        self.horizontalLayout_4.addWidget(self.btnSetSelectedDateToday)
        self.btnSetSelectedDateNext = QtWidgets.QToolButton(self.groupBox_2)
        self.btnSetSelectedDateNext.setObjectName("btnSetSelectedDateNext")
        self.horizontalLayout_4.addWidget(self.btnSetSelectedDateNext)
        self.selectedDate = QtWidgets.QDateEdit(self.groupBox_2)
        self.selectedDate.setTime(QtCore.QTime(1, 0, 0))
        self.selectedDate.setCurrentSection(QtWidgets.QDateTimeEdit.DaySection)
        self.selectedDate.setCalendarPopup(True)
        self.selectedDate.setObjectName("selectedDate")
        self.horizontalLayout_4.addWidget(self.selectedDate)
        self.reportsWeekday = QtWidgets.QLabel(self.groupBox_2)
        self.reportsWeekday.setObjectName("reportsWeekday")
        self.horizontalLayout_4.addWidget(self.reportsWeekday)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.line = QtWidgets.QFrame(self.groupBox_2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.tableReports = QtWidgets.QTableWidget(self.groupBox_2)
        self.tableReports.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableReports.setAutoScroll(False)
        self.tableReports.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableReports.setAlternatingRowColors(False)
        self.tableReports.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableReports.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableReports.setObjectName("tableReports")
        self.tableReports.setColumnCount(0)
        self.tableReports.setRowCount(0)
        self.tableReports.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_2.addWidget(self.tableReports)
        self.groupBox_3 = QtWidgets.QGroupBox(self.splitter_1)
        self.groupBox_3.setFlat(False)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnReportSave = QtWidgets.QToolButton(self.groupBox_3)
        self.btnReportSave.setObjectName("btnReportSave")
        self.horizontalLayout_2.addWidget(self.btnReportSave)
        self.btnReportNew = QtWidgets.QToolButton(self.groupBox_3)
        self.btnReportNew.setObjectName("btnReportNew")
        self.horizontalLayout_2.addWidget(self.btnReportNew)
        self.btnReportDelete = QtWidgets.QToolButton(self.groupBox_3)
        self.btnReportDelete.setObjectName("btnReportDelete")
        self.horizontalLayout_2.addWidget(self.btnReportDelete)
        self.btnReportCancel = QtWidgets.QToolButton(self.groupBox_3)
        self.btnReportCancel.setObjectName("btnReportCancel")
        self.horizontalLayout_2.addWidget(self.btnReportCancel)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.line_2 = QtWidgets.QFrame(self.groupBox_3)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_3.addWidget(self.line_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 8, 0, 1, 1)
        self.txtReportComment = QtWidgets.QTextEdit(self.groupBox_3)
        self.txtReportComment.setObjectName("txtReportComment")
        self.gridLayout.addWidget(self.txtReportComment, 8, 1, 1, 1)
        self.comboReportActivity = QtWidgets.QComboBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboReportActivity.sizePolicy().hasHeightForWidth())
        self.comboReportActivity.setSizePolicy(sizePolicy)
        self.comboReportActivity.setObjectName("comboReportActivity")
        self.gridLayout.addWidget(self.comboReportActivity, 1, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 6, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_3)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 2, 0, 1, 1)
        self.comboReportProject = QtWidgets.QComboBox(self.groupBox_3)
        self.comboReportProject.setObjectName("comboReportProject")
        self.gridLayout.addWidget(self.comboReportProject, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 7, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.dtReportStop = QtWidgets.QDateTimeEdit(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dtReportStop.sizePolicy().hasHeightForWidth())
        self.dtReportStop.setSizePolicy(sizePolicy)
        self.dtReportStop.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.dtReportStop.setCurrentSection(QtWidgets.QDateTimeEdit.YearSection)
        self.dtReportStop.setCalendarPopup(True)
        self.dtReportStop.setObjectName("dtReportStop")
        self.horizontalLayout_8.addWidget(self.dtReportStop)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.btnStopHourPlus = QtWidgets.QToolButton(self.groupBox_3)
        self.btnStopHourPlus.setObjectName("btnStopHourPlus")
        self.horizontalLayout_8.addWidget(self.btnStopHourPlus)
        self.btnStopHourMinus = QtWidgets.QToolButton(self.groupBox_3)
        self.btnStopHourMinus.setObjectName("btnStopHourMinus")
        self.horizontalLayout_8.addWidget(self.btnStopHourMinus)
        self.btnStopMinutePlus = QtWidgets.QToolButton(self.groupBox_3)
        self.btnStopMinutePlus.setAutoRepeat(True)
        self.btnStopMinutePlus.setObjectName("btnStopMinutePlus")
        self.horizontalLayout_8.addWidget(self.btnStopMinutePlus)
        self.btnStopMinuteMinus = QtWidgets.QToolButton(self.groupBox_3)
        self.btnStopMinuteMinus.setAutoRepeat(True)
        self.btnStopMinuteMinus.setObjectName("btnStopMinuteMinus")
        self.horizontalLayout_8.addWidget(self.btnStopMinuteMinus)
        self.gridLayout.addLayout(self.horizontalLayout_8, 6, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.timeReportLen = QtWidgets.QTimeEdit(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeReportLen.sizePolicy().hasHeightForWidth())
        self.timeReportLen.setSizePolicy(sizePolicy)
        self.timeReportLen.setObjectName("timeReportLen")
        self.horizontalLayout_5.addWidget(self.timeReportLen)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.gridLayout.addLayout(self.horizontalLayout_5, 7, 1, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.dtReportStart = QtWidgets.QDateTimeEdit(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dtReportStart.sizePolicy().hasHeightForWidth())
        self.dtReportStart.setSizePolicy(sizePolicy)
        self.dtReportStart.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.dtReportStart.setCalendarPopup(True)
        self.dtReportStart.setObjectName("dtReportStart")
        self.horizontalLayout_9.addWidget(self.dtReportStart)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem4)
        self.btnStartHourPlus = QtWidgets.QToolButton(self.groupBox_3)
        self.btnStartHourPlus.setAutoRepeat(False)
        self.btnStartHourPlus.setObjectName("btnStartHourPlus")
        self.horizontalLayout_9.addWidget(self.btnStartHourPlus)
        self.btnStartHourMinus = QtWidgets.QToolButton(self.groupBox_3)
        self.btnStartHourMinus.setAutoRepeat(False)
        self.btnStartHourMinus.setObjectName("btnStartHourMinus")
        self.horizontalLayout_9.addWidget(self.btnStartHourMinus)
        self.btnStartMinutePlus = QtWidgets.QToolButton(self.groupBox_3)
        self.btnStartMinutePlus.setAutoRepeat(True)
        self.btnStartMinutePlus.setObjectName("btnStartMinutePlus")
        self.horizontalLayout_9.addWidget(self.btnStartMinutePlus)
        self.btnStartMinuteMinus = QtWidgets.QToolButton(self.groupBox_3)
        self.btnStartMinuteMinus.setAutoRepeat(True)
        self.btnStartMinuteMinus.setObjectName("btnStartMinuteMinus")
        self.horizontalLayout_9.addWidget(self.btnStartMinuteMinus)
        self.gridLayout.addLayout(self.horizontalLayout_9, 3, 1, 1, 1)
        self.lblReportSyncState = QtWidgets.QLineEdit(self.groupBox_3)
        self.lblReportSyncState.setReadOnly(True)
        self.lblReportSyncState.setObjectName("lblReportSyncState")
        self.gridLayout.addWidget(self.lblReportSyncState, 0, 1, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.groupHistory = QtWidgets.QGroupBox(self.splitter_2)
        self.groupHistory.setObjectName("groupHistory")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupHistory)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.txtLog = QtWidgets.QPlainTextEdit(self.groupHistory)
        self.txtLog.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.txtLog.setReadOnly(True)
        self.txtLog.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.txtLog.setObjectName("txtLog")
        self.horizontalLayout.addWidget(self.txtLog)
        self.verticalLayout.addWidget(self.splitter_2)
        Main.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Main)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 807, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuActivity = QtWidgets.QMenu(self.menubar)
        self.menuActivity.setObjectName("menuActivity")
        self.menuReport = QtWidgets.QMenu(self.menubar)
        self.menuReport.setObjectName("menuReport")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        Main.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Main)
        self.statusbar.setObjectName("statusbar")
        Main.setStatusBar(self.statusbar)
        self.actionAbout = QtWidgets.QAction(Main)
        self.actionAbout.setObjectName("actionAbout")
        self.actionSettings = QtWidgets.QAction(Main)
        self.actionSettings.setObjectName("actionSettings")
        self.actionShortlist = QtWidgets.QAction(Main)
        self.actionShortlist.setObjectName("actionShortlist")
        self.actionActivitySync = QtWidgets.QAction(Main)
        self.actionActivitySync.setObjectName("actionActivitySync")
        self.actionReportSync = QtWidgets.QAction(Main)
        self.actionReportSync.setObjectName("actionReportSync")
        self.actionNew = QtWidgets.QAction(Main)
        self.actionNew.setObjectName("actionNew")
        self.actionServer_web_page = QtWidgets.QAction(Main)
        self.actionServer_web_page.setObjectName("actionServer_web_page")
        self.actionDocumentation = QtWidgets.QAction(Main)
        self.actionDocumentation.setObjectName("actionDocumentation")
        self.actionExit = QtWidgets.QAction(Main)
        self.actionExit.setObjectName("actionExit")
        self.actionSave_windows_position = QtWidgets.QAction(Main)
        self.actionSave_windows_position.setObjectName("actionSave_windows_position")
        self.actionLoad_windows_position = QtWidgets.QAction(Main)
        self.actionLoad_windows_position.setObjectName("actionLoad_windows_position")
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionSettings)
        self.menuEdit.addAction(self.actionShortlist)
        self.menuEdit.addAction(self.actionSave_windows_position)
        self.menuActivity.addAction(self.actionActivitySync)
        self.menuReport.addAction(self.actionReportSync)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuActivity.menuAction())
        self.menubar.addAction(self.menuReport.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(Main)
        QtCore.QMetaObject.connectSlotsByName(Main)
        Main.setTabOrder(self.dtReportStart, self.dtReportStop)
        Main.setTabOrder(self.dtReportStop, self.comboCurrentActivity)
        Main.setTabOrder(self.comboCurrentActivity, self.dtCurrentStart)
        Main.setTabOrder(self.dtCurrentStart, self.timeCurrentLen)
        Main.setTabOrder(self.timeCurrentLen, self.btnCurrentStart)
        Main.setTabOrder(self.btnCurrentStart, self.btnCurrentStop)
        Main.setTabOrder(self.btnCurrentStop, self.txtCurrentComment)
        Main.setTabOrder(self.txtCurrentComment, self.btnReportSync)
        Main.setTabOrder(self.btnReportSync, self.chkReportSyncAuto)
        Main.setTabOrder(self.chkReportSyncAuto, self.btnSetSelectedDatePrev)
        Main.setTabOrder(self.btnSetSelectedDatePrev, self.btnSetSelectedDateToday)
        Main.setTabOrder(self.btnSetSelectedDateToday, self.btnSetSelectedDateNext)
        Main.setTabOrder(self.btnSetSelectedDateNext, self.selectedDate)
        Main.setTabOrder(self.selectedDate, self.tableReports)
        Main.setTabOrder(self.tableReports, self.btnReportSave)
        Main.setTabOrder(self.btnReportSave, self.btnReportNew)
        Main.setTabOrder(self.btnReportNew, self.btnReportDelete)
        Main.setTabOrder(self.btnReportDelete, self.btnReportCancel)
        Main.setTabOrder(self.btnReportCancel, self.timeReportLen)
        Main.setTabOrder(self.timeReportLen, self.btnStartHourPlus)
        Main.setTabOrder(self.btnStartHourPlus, self.btnStartHourMinus)
        Main.setTabOrder(self.btnStartHourMinus, self.btnStartMinutePlus)
        Main.setTabOrder(self.btnStartMinutePlus, self.btnStartMinuteMinus)
        Main.setTabOrder(self.btnStartMinuteMinus, self.txtReportComment)
        Main.setTabOrder(self.txtReportComment, self.btnStopHourPlus)
        Main.setTabOrder(self.btnStopHourPlus, self.btnStopHourMinus)
        Main.setTabOrder(self.btnStopHourMinus, self.btnStopMinutePlus)
        Main.setTabOrder(self.btnStopMinutePlus, self.btnStopMinuteMinus)
        Main.setTabOrder(self.btnStopMinuteMinus, self.txtLog)

    def retranslateUi(self, Main):
        _translate = QtCore.QCoreApplication.translate
        Main.setWindowTitle(_translate("Main", "ErgoTime"))
        self.horizontalGroupBox_2.setTitle(_translate("Main", "Current Report"))
        self.label_3.setText(_translate("Main", "Activity"))
        self.label_5.setText(_translate("Main", "Length"))
        self.label_4.setText(_translate("Main", "Start"))
        self.dtCurrentStart.setDisplayFormat(_translate("Main", "yyyy-MM-dd HH:mm"))
        self.timeCurrentLen.setDisplayFormat(_translate("Main", "HH:mm:ss"))
        self.btnCurrentStart.setText(_translate("Main", "Start"))
        self.btnCurrentStop.setText(_translate("Main", "Stop"))
        self.groupBox.setTitle(_translate("Main", "Comment"))
        self.label_11.setText(_translate("Main", "Project"))
        self.groupBox_2.setTitle(_translate("Main", "Reports"))
        self.btnReportSync.setText(_translate("Main", "Sync"))
        self.chkReportSyncAuto.setText(_translate("Main", "Auto"))
        self.btnSetSelectedDatePrev.setText(_translate("Main", "<"))
        self.btnSetSelectedDateToday.setText(_translate("Main", "Today"))
        self.btnSetSelectedDateNext.setText(_translate("Main", ">"))
        self.reportsWeekday.setText(_translate("Main", "<weekday>"))
        self.groupBox_3.setTitle(_translate("Main", "Report details"))
        self.btnReportSave.setText(_translate("Main", "Save"))
        self.btnReportNew.setText(_translate("Main", "New"))
        self.btnReportDelete.setText(_translate("Main", "Delete"))
        self.btnReportCancel.setText(_translate("Main", "Cancel"))
        self.label_9.setText(_translate("Main", "Comment"))
        self.label_10.setText(_translate("Main", "Stop"))
        self.label_12.setText(_translate("Main", "Project"))
        self.label_2.setText(_translate("Main", "Sync state"))
        self.label_8.setText(_translate("Main", "   Length"))
        self.label_6.setText(_translate("Main", "Activity"))
        self.dtReportStop.setDisplayFormat(_translate("Main", "yyyy-MM-dd HH:mm"))
        self.btnStopHourPlus.setText(_translate("Main", "+H"))
        self.btnStopHourMinus.setText(_translate("Main", "-H"))
        self.btnStopMinutePlus.setText(_translate("Main", "+M"))
        self.btnStopMinuteMinus.setText(_translate("Main", "-M"))
        self.label_7.setText(_translate("Main", "Start"))
        self.timeReportLen.setDisplayFormat(_translate("Main", "HH:mm"))
        self.dtReportStart.setDisplayFormat(_translate("Main", "yyyy-MM-dd HH:mm"))
        self.btnStartHourPlus.setText(_translate("Main", "+H"))
        self.btnStartHourMinus.setText(_translate("Main", "-H"))
        self.btnStartMinutePlus.setText(_translate("Main", "+M"))
        self.btnStartMinuteMinus.setText(_translate("Main", "-M"))
        self.groupHistory.setTitle(_translate("Main", "History"))
        self.menuFile.setTitle(_translate("Main", "File"))
        self.menuEdit.setTitle(_translate("Main", "Edit"))
        self.menuActivity.setTitle(_translate("Main", "Activity"))
        self.menuReport.setTitle(_translate("Main", "Report"))
        self.menuHelp.setTitle(_translate("Main", "Help"))
        self.actionAbout.setText(_translate("Main", "About"))
        self.actionSettings.setText(_translate("Main", "Settings"))
        self.actionShortlist.setText(_translate("Main", "Shortlist"))
        self.actionActivitySync.setText(_translate("Main", "Sync"))
        self.actionReportSync.setText(_translate("Main", "Sync"))
        self.actionNew.setText(_translate("Main", "New"))
        self.actionServer_web_page.setText(_translate("Main", "Server web page"))
        self.actionDocumentation.setText(_translate("Main", "Documentation"))
        self.actionExit.setText(_translate("Main", "Exit"))
        self.actionSave_windows_position.setText(_translate("Main", "Save windows position"))
        self.actionLoad_windows_position.setText(_translate("Main", "Load windows position"))

