# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'options_win.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Options(object):
    def setupUi(self, Options):
        Options.setObjectName("Options")
        Options.setWindowModality(QtCore.Qt.WindowModal)
        Options.resize(1011, 450)
        self.verticalLayout = QtWidgets.QVBoxLayout(Options)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(Options)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout = QtWidgets.QGridLayout(self.tab)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 4, 1, 1)
        self.comboLoglevel = QtWidgets.QComboBox(self.tab)
        self.comboLoglevel.setEditable(False)
        self.comboLoglevel.setObjectName("comboLoglevel")
        self.gridLayout.addWidget(self.comboLoglevel, 5, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 6, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.txtUsername = QtWidgets.QLineEdit(self.tab)
        self.txtUsername.setObjectName("txtUsername")
        self.gridLayout.addWidget(self.txtUsername, 1, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.comboFontName = QtWidgets.QFontComboBox(self.tab)
        self.comboFontName.setObjectName("comboFontName")
        self.gridLayout.addWidget(self.comboFontName, 0, 2, 1, 1)
        self.txtDatabasedir = QtWidgets.QLineEdit(self.tab)
        self.txtDatabasedir.setObjectName("txtDatabasedir")
        self.gridLayout.addWidget(self.txtDatabasedir, 4, 2, 1, 3)
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
        self.txtPassword = QtWidgets.QLineEdit(self.tab)
        self.txtPassword.setObjectName("txtPassword")
        self.gridLayout.addWidget(self.txtPassword, 2, 2, 1, 1)
        self.spinIdleTimeout = QtWidgets.QSpinBox(self.tab)
        self.spinIdleTimeout.setAccelerated(True)
        self.spinIdleTimeout.setMaximum(3600)
        self.spinIdleTimeout.setProperty("value", 0)
        self.spinIdleTimeout.setObjectName("spinIdleTimeout")
        self.gridLayout.addWidget(self.spinIdleTimeout, 3, 2, 1, 1)
        self.comboFontSize = QtWidgets.QComboBox(self.tab)
        self.comboFontSize.setEditable(True)
        self.comboFontSize.setObjectName("comboFontSize")
        self.gridLayout.addWidget(self.comboFontSize, 0, 3, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 0, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 1, 0, 1, 1)
        self.spinActivitySyncInterval = QtWidgets.QSpinBox(self.tab_2)
        self.spinActivitySyncInterval.setMaximum(86400)
        self.spinActivitySyncInterval.setObjectName("spinActivitySyncInterval")
        self.gridLayout_2.addWidget(self.spinActivitySyncInterval, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_8 = QtWidgets.QLabel(self.tab_3)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 0, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(185, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem4, 0, 2, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem5, 1, 0, 1, 1)
        self.spinReportSyncInterval = QtWidgets.QSpinBox(self.tab_3)
        self.spinReportSyncInterval.setMaximum(86400)
        self.spinReportSyncInterval.setObjectName("spinReportSyncInterval")
        self.gridLayout_3.addWidget(self.spinReportSyncInterval, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_9 = QtWidgets.QLabel(self.tab_4)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 0, 0, 1, 1)
        self.spinNetworkTimeout = QtWidgets.QSpinBox(self.tab_4)
        self.spinNetworkTimeout.setMinimum(1)
        self.spinNetworkTimeout.setMaximum(180)
        self.spinNetworkTimeout.setProperty("value", 60)
        self.spinNetworkTimeout.setObjectName("spinNetworkTimeout")
        self.gridLayout_4.addWidget(self.spinNetworkTimeout, 1, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.tab_4)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_4.addWidget(self.label_11, 1, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem6, 2, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem7, 1, 3, 1, 1)
        self.txtServerUrl = QtWidgets.QLineEdit(self.tab_4)
        self.txtServerUrl.setObjectName("txtServerUrl")
        self.gridLayout_4.addWidget(self.txtServerUrl, 0, 2, 1, 2)
        self.tabWidget.addTab(self.tab_4, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem8)
        self.btnOk = QtWidgets.QPushButton(Options)
        self.btnOk.setObjectName("btnOk")
        self.horizontalLayout.addWidget(self.btnOk)
        self.btnCancel = QtWidgets.QPushButton(Options)
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout.addWidget(self.btnCancel)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Options)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Options)
        Options.setTabOrder(self.comboFontName, self.txtUsername)
        Options.setTabOrder(self.txtUsername, self.txtPassword)
        Options.setTabOrder(self.txtPassword, self.txtDatabasedir)
        Options.setTabOrder(self.txtDatabasedir, self.comboLoglevel)
        Options.setTabOrder(self.comboLoglevel, self.txtServerUrl)
        Options.setTabOrder(self.txtServerUrl, self.btnOk)
        Options.setTabOrder(self.btnOk, self.btnCancel)
        Options.setTabOrder(self.btnCancel, self.tabWidget)

    def retranslateUi(self, Options):
        _translate = QtCore.QCoreApplication.translate
        Options.setWindowTitle(_translate("Options", "Ergotime Options"))
        self.label_2.setText(_translate("Options", "Username"))
        self.label_5.setText(_translate("Options", "Log Level"))
        self.label_4.setText(_translate("Options", "Database directory"))
        self.label.setText(_translate("Options", "Font"))
        self.label_3.setText(_translate("Options", "Idle timeout, seconds"))
        self.label_6.setText(_translate("Options", "Password"))
        self.txtPassword.setToolTip(_translate("Options", "If empty, user will be prompted for the password"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Options", "General"))
        self.label_7.setText(_translate("Options", "Periodic sync interval, in seconds"))
        self.spinActivitySyncInterval.setToolTip(_translate("Options", "If zero, disabled"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Options", "Activity"))
        self.label_8.setText(_translate("Options", "Periodic sync interval, in seconds"))
        self.spinReportSyncInterval.setToolTip(_translate("Options", "If zero, disabled"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Options", "Report"))
        self.label_9.setText(_translate("Options", "Server URL"))
        self.label_11.setText(_translate("Options", "Timeout"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Options", "Network"))
        self.btnOk.setText(_translate("Options", "OK"))
        self.btnCancel.setText(_translate("Options", "Cancel"))

