# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'report_win.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Report(object):
    def setupUi(self, Report):
        Report.setObjectName("Report")
        Report.resize(678, 385)
        self.verticalLayout = QtWidgets.QVBoxLayout(Report)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(Report)
        self.groupBox_3.setFlat(False)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnSave = QtWidgets.QToolButton(self.groupBox_3)
        self.btnSave.setObjectName("btnSave")
        self.horizontalLayout_2.addWidget(self.btnSave)
        self.btnDelete = QtWidgets.QToolButton(self.groupBox_3)
        self.btnDelete.setObjectName("btnDelete")
        self.horizontalLayout_2.addWidget(self.btnDelete)
        self.btnCancel = QtWidgets.QToolButton(self.groupBox_3)
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout_2.addWidget(self.btnCancel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.line_2 = QtWidgets.QFrame(self.groupBox_3)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_3.addWidget(self.line_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 8, 0, 1, 1)
        self.txtComment = QtWidgets.QTextEdit(self.groupBox_3)
        self.txtComment.setObjectName("txtComment")
        self.gridLayout.addWidget(self.txtComment, 8, 1, 1, 1)
        self.comboActivity = QtWidgets.QComboBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboActivity.sizePolicy().hasHeightForWidth())
        self.comboActivity.setSizePolicy(sizePolicy)
        self.comboActivity.setObjectName("comboActivity")
        self.gridLayout.addWidget(self.comboActivity, 1, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 6, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_3)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 2, 0, 1, 1)
        self.comboProject = QtWidgets.QComboBox(self.groupBox_3)
        self.comboProject.setObjectName("comboProject")
        self.gridLayout.addWidget(self.comboProject, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 7, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.dtStop = QtWidgets.QDateTimeEdit(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dtStop.sizePolicy().hasHeightForWidth())
        self.dtStop.setSizePolicy(sizePolicy)
        self.dtStop.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.dtStop.setCurrentSection(QtWidgets.QDateTimeEdit.YearSection)
        self.dtStop.setCalendarPopup(True)
        self.dtStop.setObjectName("dtStop")
        self.horizontalLayout_8.addWidget(self.dtStop)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem1)
        self.btnStopHourPlus = QtWidgets.QToolButton(self.groupBox_3)
        self.btnStopHourPlus.setObjectName("btnStopHourPlus")
        self.horizontalLayout_8.addWidget(self.btnStopHourPlus)
        self.btnStopHourMinus = QtWidgets.QToolButton(self.groupBox_3)
        self.btnStopHourMinus.setObjectName("btnStopHourMinus")
        self.horizontalLayout_8.addWidget(self.btnStopHourMinus)
        self.btnStopMinutePlus = QtWidgets.QToolButton(self.groupBox_3)
        self.btnStopMinutePlus.setAutoRepeat(True)
        self.btnStopMinutePlus.setObjectName("btnStopMinutePlus")
        self.horizontalLayout_8.addWidget(self.btnStopMinutePlus)
        self.btnStopMinuteMinus = QtWidgets.QToolButton(self.groupBox_3)
        self.btnStopMinuteMinus.setAutoRepeat(True)
        self.btnStopMinuteMinus.setObjectName("btnStopMinuteMinus")
        self.horizontalLayout_8.addWidget(self.btnStopMinuteMinus)
        self.gridLayout.addLayout(self.horizontalLayout_8, 6, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.timeLen = QtWidgets.QTimeEdit(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeLen.sizePolicy().hasHeightForWidth())
        self.timeLen.setSizePolicy(sizePolicy)
        self.timeLen.setObjectName("timeLen")
        self.horizontalLayout_5.addWidget(self.timeLen)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.gridLayout.addLayout(self.horizontalLayout_5, 7, 1, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.dtStart = QtWidgets.QDateTimeEdit(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dtStart.sizePolicy().hasHeightForWidth())
        self.dtStart.setSizePolicy(sizePolicy)
        self.dtStart.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.dtStart.setCalendarPopup(True)
        self.dtStart.setObjectName("dtStart")
        self.horizontalLayout_9.addWidget(self.dtStart)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem3)
        self.btnStartHourPlus = QtWidgets.QToolButton(self.groupBox_3)
        self.btnStartHourPlus.setAutoRepeat(False)
        self.btnStartHourPlus.setObjectName("btnStartHourPlus")
        self.horizontalLayout_9.addWidget(self.btnStartHourPlus)
        self.btnStartHourMinus = QtWidgets.QToolButton(self.groupBox_3)
        self.btnStartHourMinus.setAutoRepeat(False)
        self.btnStartHourMinus.setObjectName("btnStartHourMinus")
        self.horizontalLayout_9.addWidget(self.btnStartHourMinus)
        self.btnStartMinutePlus = QtWidgets.QToolButton(self.groupBox_3)
        self.btnStartMinutePlus.setAutoRepeat(True)
        self.btnStartMinutePlus.setObjectName("btnStartMinutePlus")
        self.horizontalLayout_9.addWidget(self.btnStartMinutePlus)
        self.btnStartMinuteMinus = QtWidgets.QToolButton(self.groupBox_3)
        self.btnStartMinuteMinus.setAutoRepeat(True)
        self.btnStartMinuteMinus.setObjectName("btnStartMinuteMinus")
        self.horizontalLayout_9.addWidget(self.btnStartMinuteMinus)
        self.gridLayout.addLayout(self.horizontalLayout_9, 3, 1, 1, 1)
        self.lblSyncState = QtWidgets.QLineEdit(self.groupBox_3)
        self.lblSyncState.setReadOnly(True)
        self.lblSyncState.setObjectName("lblSyncState")
        self.gridLayout.addWidget(self.lblSyncState, 0, 1, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.actionAbout = QtWidgets.QAction(Report)
        self.actionAbout.setObjectName("actionAbout")
        self.actionSettings = QtWidgets.QAction(Report)
        self.actionSettings.setObjectName("actionSettings")
        self.actionShortlist = QtWidgets.QAction(Report)
        self.actionShortlist.setObjectName("actionShortlist")
        self.actionActivitySync = QtWidgets.QAction(Report)
        self.actionActivitySync.setObjectName("actionActivitySync")
        self.actionReportSync = QtWidgets.QAction(Report)
        self.actionReportSync.setObjectName("actionReportSync")
        self.actionNew = QtWidgets.QAction(Report)
        self.actionNew.setObjectName("actionNew")
        self.actionServer_web_page = QtWidgets.QAction(Report)
        self.actionServer_web_page.setObjectName("actionServer_web_page")
        self.actionDocumentation = QtWidgets.QAction(Report)
        self.actionDocumentation.setObjectName("actionDocumentation")
        self.actionExit = QtWidgets.QAction(Report)
        self.actionExit.setObjectName("actionExit")
        self.actionSave_windows_position = QtWidgets.QAction(Report)
        self.actionSave_windows_position.setObjectName("actionSave_windows_position")
        self.actionLoad_windows_position = QtWidgets.QAction(Report)
        self.actionLoad_windows_position.setObjectName("actionLoad_windows_position")

        self.retranslateUi(Report)
        QtCore.QMetaObject.connectSlotsByName(Report)
        Report.setTabOrder(self.dtStart, self.dtStop)
        Report.setTabOrder(self.dtStop, self.btnSave)
        Report.setTabOrder(self.btnSave, self.btnDelete)
        Report.setTabOrder(self.btnDelete, self.btnCancel)
        Report.setTabOrder(self.btnCancel, self.timeLen)
        Report.setTabOrder(self.timeLen, self.btnStartHourPlus)
        Report.setTabOrder(self.btnStartHourPlus, self.btnStartHourMinus)
        Report.setTabOrder(self.btnStartHourMinus, self.btnStartMinutePlus)
        Report.setTabOrder(self.btnStartMinutePlus, self.btnStartMinuteMinus)
        Report.setTabOrder(self.btnStartMinuteMinus, self.txtComment)
        Report.setTabOrder(self.txtComment, self.btnStopHourPlus)
        Report.setTabOrder(self.btnStopHourPlus, self.btnStopHourMinus)
        Report.setTabOrder(self.btnStopHourMinus, self.btnStopMinutePlus)
        Report.setTabOrder(self.btnStopMinutePlus, self.btnStopMinuteMinus)

    def retranslateUi(self, Report):
        _translate = QtCore.QCoreApplication.translate
        Report.setWindowTitle(_translate("Report", "ErgoTime"))
        self.groupBox_3.setTitle(_translate("Report", "Report details"))
        self.btnSave.setText(_translate("Report", "Save"))
        self.btnDelete.setText(_translate("Report", "Delete"))
        self.btnCancel.setText(_translate("Report", "Cancel"))
        self.label_9.setText(_translate("Report", "Comment"))
        self.label_10.setText(_translate("Report", "Stop"))
        self.label_12.setText(_translate("Report", "Project"))
        self.label_2.setText(_translate("Report", "Sync state"))
        self.label_8.setText(_translate("Report", "   Length"))
        self.label_6.setText(_translate("Report", "Activity"))
        self.dtStop.setDisplayFormat(_translate("Report", "yyyy-MM-dd HH:mm"))
        self.btnStopHourPlus.setText(_translate("Report", "+H"))
        self.btnStopHourMinus.setText(_translate("Report", "-H"))
        self.btnStopMinutePlus.setText(_translate("Report", "+M"))
        self.btnStopMinuteMinus.setText(_translate("Report", "-M"))
        self.label_7.setText(_translate("Report", "Start"))
        self.timeLen.setDisplayFormat(_translate("Report", "HH:mm"))
        self.dtStart.setDisplayFormat(_translate("Report", "yyyy-MM-dd HH:mm"))
        self.btnStartHourPlus.setText(_translate("Report", "+H"))
        self.btnStartHourMinus.setText(_translate("Report", "-H"))
        self.btnStartMinutePlus.setText(_translate("Report", "+M"))
        self.btnStartMinuteMinus.setText(_translate("Report", "-M"))
        self.actionAbout.setText(_translate("Report", "About"))
        self.actionSettings.setText(_translate("Report", "Settings"))
        self.actionShortlist.setText(_translate("Report", "Shortlist"))
        self.actionActivitySync.setText(_translate("Report", "Sync"))
        self.actionReportSync.setText(_translate("Report", "Sync"))
        self.actionNew.setText(_translate("Report", "New"))
        self.actionServer_web_page.setText(_translate("Report", "Server web page"))
        self.actionDocumentation.setText(_translate("Report", "Documentation"))
        self.actionExit.setText(_translate("Report", "Exit"))
        self.actionSave_windows_position.setText(_translate("Report", "Save windows position"))
        self.actionLoad_windows_position.setText(_translate("Report", "Load windows position"))

