# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\hack\eclipse\ErgoTime\ui_main.ui'
#
# Created: Thu Nov 14 01:57:07 2013
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Main(object):
    def setupUi(self, Main):
        Main.setObjectName("Main")
        Main.resize(807, 594)
        self.centralwidget = QtGui.QWidget(Main)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalGroupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.horizontalGroupBox_2.setObjectName("horizontalGroupBox_2")
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.horizontalGroupBox_2)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_4 = QtGui.QLabel(self.horizontalGroupBox_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 1, 0, 1, 1)
        self.comboCurrentActivity = QtGui.QComboBox(self.horizontalGroupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboCurrentActivity.sizePolicy().hasHeightForWidth())
        self.comboCurrentActivity.setSizePolicy(sizePolicy)
        self.comboCurrentActivity.setObjectName("comboCurrentActivity")
        self.gridLayout_3.addWidget(self.comboCurrentActivity, 0, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.horizontalGroupBox_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.horizontalGroupBox_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 2, 0, 1, 1)
        self.dtCurrentStart = QtGui.QDateTimeEdit(self.horizontalGroupBox_2)
        self.dtCurrentStart.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dtCurrentStart.setCurrentSection(QtGui.QDateTimeEdit.YearSection)
        self.dtCurrentStart.setCalendarPopup(False)
        self.dtCurrentStart.setObjectName("dtCurrentStart")
        self.gridLayout_3.addWidget(self.dtCurrentStart, 1, 1, 1, 1)
        self.timeCurrentLen = QtGui.QTimeEdit(self.horizontalGroupBox_2)
        self.timeCurrentLen.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.timeCurrentLen.setCurrentSection(QtGui.QDateTimeEdit.HourSection)
        self.timeCurrentLen.setObjectName("timeCurrentLen")
        self.gridLayout_3.addWidget(self.timeCurrentLen, 2, 1, 1, 1)
        self.btnCurrentStart = QtGui.QToolButton(self.horizontalGroupBox_2)
        self.btnCurrentStart.setObjectName("btnCurrentStart")
        self.gridLayout_3.addWidget(self.btnCurrentStart, 0, 3, 1, 1)
        self.btnCurrentStop = QtGui.QToolButton(self.horizontalGroupBox_2)
        self.btnCurrentStop.setObjectName("btnCurrentStop")
        self.gridLayout_3.addWidget(self.btnCurrentStop, 1, 3, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.horizontalGroupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_10.setSpacing(3)
        self.horizontalLayout_10.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.txtCurrentComment = QtGui.QTextEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtCurrentComment.sizePolicy().hasHeightForWidth())
        self.txtCurrentComment.setSizePolicy(sizePolicy)
        self.txtCurrentComment.setAcceptRichText(False)
        self.txtCurrentComment.setObjectName("txtCurrentComment")
        self.horizontalLayout_10.addWidget(self.txtCurrentComment)
        self.gridLayout_3.addWidget(self.groupBox, 0, 2, 3, 1)
        self.horizontalLayout_7.addLayout(self.gridLayout_3)
        self.verticalLayout.addWidget(self.horizontalGroupBox_2)
        self.splitter_2 = QtGui.QSplitter(self.centralwidget)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.splitter = QtGui.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.groupBox_2 = QtGui.QGroupBox(self.splitter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btnReportSync = QtGui.QToolButton(self.groupBox_2)
        self.btnReportSync.setObjectName("btnReportSync")
        self.horizontalLayout_4.addWidget(self.btnReportSync)
        self.chkReportSyncAuto = QtGui.QCheckBox(self.groupBox_2)
        self.chkReportSyncAuto.setObjectName("chkReportSyncAuto")
        self.horizontalLayout_4.addWidget(self.chkReportSyncAuto)
        self.btnSetSelectedDatePrev = QtGui.QToolButton(self.groupBox_2)
        self.btnSetSelectedDatePrev.setObjectName("btnSetSelectedDatePrev")
        self.horizontalLayout_4.addWidget(self.btnSetSelectedDatePrev)
        self.btnSetSelectedDateToday = QtGui.QToolButton(self.groupBox_2)
        self.btnSetSelectedDateToday.setObjectName("btnSetSelectedDateToday")
        self.horizontalLayout_4.addWidget(self.btnSetSelectedDateToday)
        self.btnSetSelectedDateNext = QtGui.QToolButton(self.groupBox_2)
        self.btnSetSelectedDateNext.setObjectName("btnSetSelectedDateNext")
        self.horizontalLayout_4.addWidget(self.btnSetSelectedDateNext)
        self.selectedDate = QtGui.QDateEdit(self.groupBox_2)
        self.selectedDate.setTime(QtCore.QTime(1, 0, 0))
        self.selectedDate.setCurrentSection(QtGui.QDateTimeEdit.DaySection)
        self.selectedDate.setCalendarPopup(True)
        self.selectedDate.setObjectName("selectedDate")
        self.horizontalLayout_4.addWidget(self.selectedDate)
        self.reportsWeekday = QtGui.QLabel(self.groupBox_2)
        self.reportsWeekday.setObjectName("reportsWeekday")
        self.horizontalLayout_4.addWidget(self.reportsWeekday)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.line = QtGui.QFrame(self.groupBox_2)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.tableReports = QtGui.QTableWidget(self.groupBox_2)
        self.tableReports.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableReports.setAlternatingRowColors(False)
        self.tableReports.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tableReports.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableReports.setObjectName("tableReports")
        self.tableReports.setColumnCount(0)
        self.tableReports.setRowCount(0)
        self.verticalLayout_2.addWidget(self.tableReports)
        self.groupBox_3 = QtGui.QGroupBox(self.splitter)
        self.groupBox_3.setFlat(False)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnReportSave = QtGui.QToolButton(self.groupBox_3)
        self.btnReportSave.setObjectName("btnReportSave")
        self.horizontalLayout_2.addWidget(self.btnReportSave)
        self.btnReportNew = QtGui.QToolButton(self.groupBox_3)
        self.btnReportNew.setObjectName("btnReportNew")
        self.horizontalLayout_2.addWidget(self.btnReportNew)
        self.btnReportRemove = QtGui.QToolButton(self.groupBox_3)
        self.btnReportRemove.setObjectName("btnReportRemove")
        self.horizontalLayout_2.addWidget(self.btnReportRemove)
        self.btnReportCancel = QtGui.QToolButton(self.groupBox_3)
        self.btnReportCancel.setObjectName("btnReportCancel")
        self.horizontalLayout_2.addWidget(self.btnReportCancel)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.line_2 = QtGui.QFrame(self.groupBox_3)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_3.addWidget(self.line_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.timeReportLen = QtGui.QTimeEdit(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeReportLen.sizePolicy().hasHeightForWidth())
        self.timeReportLen.setSizePolicy(sizePolicy)
        self.timeReportLen.setObjectName("timeReportLen")
        self.horizontalLayout_5.addWidget(self.timeReportLen)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.gridLayout.addLayout(self.horizontalLayout_5, 8, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_3)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 4, 0, 1, 1)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.dtReportStart = QtGui.QDateTimeEdit(self.groupBox_3)
        self.dtReportStart.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.dtReportStart.setCurrentSection(QtGui.QDateTimeEdit.YearSection)
        self.dtReportStart.setCalendarPopup(True)
        self.dtReportStart.setObjectName("dtReportStart")
        self.horizontalLayout_9.addWidget(self.dtReportStart)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem3)
        self.btnStartHourPlus = QtGui.QToolButton(self.groupBox_3)
        self.btnStartHourPlus.setAutoRepeat(False)
        self.btnStartHourPlus.setObjectName("btnStartHourPlus")
        self.horizontalLayout_9.addWidget(self.btnStartHourPlus)
        self.btnStartHourMinus = QtGui.QToolButton(self.groupBox_3)
        self.btnStartHourMinus.setAutoRepeat(False)
        self.btnStartHourMinus.setObjectName("btnStartHourMinus")
        self.horizontalLayout_9.addWidget(self.btnStartHourMinus)
        self.btnStartMinutePlus = QtGui.QToolButton(self.groupBox_3)
        self.btnStartMinutePlus.setAutoRepeat(True)
        self.btnStartMinutePlus.setObjectName("btnStartMinutePlus")
        self.horizontalLayout_9.addWidget(self.btnStartMinutePlus)
        self.btnStartMinuteMinus = QtGui.QToolButton(self.groupBox_3)
        self.btnStartMinuteMinus.setAutoRepeat(True)
        self.btnStartMinuteMinus.setObjectName("btnStartMinuteMinus")
        self.horizontalLayout_9.addWidget(self.btnStartMinuteMinus)
        self.gridLayout.addLayout(self.horizontalLayout_9, 4, 1, 1, 1)
        self.txtReportComment = QtGui.QTextEdit(self.groupBox_3)
        self.txtReportComment.setObjectName("txtReportComment")
        self.gridLayout.addWidget(self.txtReportComment, 9, 1, 1, 1)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.dtReportStop = QtGui.QDateTimeEdit(self.groupBox_3)
        self.dtReportStop.setButtonSymbols(QtGui.QAbstractSpinBox.PlusMinus)
        self.dtReportStop.setCalendarPopup(True)
        self.dtReportStop.setObjectName("dtReportStop")
        self.horizontalLayout_8.addWidget(self.dtReportStop)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem4)
        self.btnStopHourPlus = QtGui.QToolButton(self.groupBox_3)
        self.btnStopHourPlus.setObjectName("btnStopHourPlus")
        self.horizontalLayout_8.addWidget(self.btnStopHourPlus)
        self.btnStopHourMinus = QtGui.QToolButton(self.groupBox_3)
        self.btnStopHourMinus.setObjectName("btnStopHourMinus")
        self.horizontalLayout_8.addWidget(self.btnStopHourMinus)
        self.btnStopMinutePlus = QtGui.QToolButton(self.groupBox_3)
        self.btnStopMinutePlus.setAutoRepeat(True)
        self.btnStopMinutePlus.setObjectName("btnStopMinutePlus")
        self.horizontalLayout_8.addWidget(self.btnStopMinutePlus)
        self.btnStopMinuteMinus = QtGui.QToolButton(self.groupBox_3)
        self.btnStopMinuteMinus.setAutoRepeat(True)
        self.btnStopMinuteMinus.setObjectName("btnStopMinuteMinus")
        self.horizontalLayout_8.addWidget(self.btnStopMinuteMinus)
        self.gridLayout.addLayout(self.horizontalLayout_8, 7, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_3)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
        self.label = QtGui.QLabel(self.groupBox_3)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lblReportSyncState = QtGui.QLabel(self.groupBox_3)
        self.lblReportSyncState.setObjectName("lblReportSyncState")
        self.gridLayout.addWidget(self.lblReportSyncState, 1, 1, 1, 1)
        self.lblReportState = QtGui.QLabel(self.groupBox_3)
        self.lblReportState.setObjectName("lblReportState")
        self.gridLayout.addWidget(self.lblReportState, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox_3)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox_3)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 8, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.groupBox_3)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 7, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox_3)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 9, 0, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.comboReportActivity = QtGui.QComboBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboReportActivity.sizePolicy().hasHeightForWidth())
        self.comboReportActivity.setSizePolicy(sizePolicy)
        self.comboReportActivity.setObjectName("comboReportActivity")
        self.horizontalLayout_6.addWidget(self.comboReportActivity)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.gridLayout.addLayout(self.horizontalLayout_6, 2, 1, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.groupHistory = QtGui.QGroupBox(self.splitter_2)
        self.groupHistory.setObjectName("groupHistory")
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupHistory)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.txtLog = QtGui.QPlainTextEdit(self.groupHistory)
        self.txtLog.setLineWrapMode(QtGui.QPlainTextEdit.NoWrap)
        self.txtLog.setReadOnly(True)
        self.txtLog.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.txtLog.setObjectName("txtLog")
        self.horizontalLayout.addWidget(self.txtLog)
        self.verticalLayout.addWidget(self.splitter_2)
        Main.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(Main)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 807, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuActivity = QtGui.QMenu(self.menubar)
        self.menuActivity.setObjectName("menuActivity")
        self.menuReport = QtGui.QMenu(self.menubar)
        self.menuReport.setObjectName("menuReport")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        Main.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(Main)
        self.statusbar.setObjectName("statusbar")
        Main.setStatusBar(self.statusbar)
        self.actionAbout = QtGui.QAction(Main)
        self.actionAbout.setObjectName("actionAbout")
        self.actionSettings = QtGui.QAction(Main)
        self.actionSettings.setObjectName("actionSettings")
        self.actionShortlist = QtGui.QAction(Main)
        self.actionShortlist.setObjectName("actionShortlist")
        self.actionActivitySync = QtGui.QAction(Main)
        self.actionActivitySync.setObjectName("actionActivitySync")
        self.actionReportSync = QtGui.QAction(Main)
        self.actionReportSync.setObjectName("actionReportSync")
        self.actionNew = QtGui.QAction(Main)
        self.actionNew.setObjectName("actionNew")
        self.actionServer_web_page = QtGui.QAction(Main)
        self.actionServer_web_page.setObjectName("actionServer_web_page")
        self.actionDocumentation = QtGui.QAction(Main)
        self.actionDocumentation.setObjectName("actionDocumentation")
        self.actionExit = QtGui.QAction(Main)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionSettings)
        self.menuEdit.addAction(self.actionShortlist)
        self.menuActivity.addAction(self.actionActivitySync)
        self.menuReport.addAction(self.actionReportSync)
        self.menuReport.addAction(self.actionNew)
        self.menuReport.addAction(self.actionServer_web_page)
        self.menuHelp.addAction(self.actionDocumentation)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuActivity.menuAction())
        self.menubar.addAction(self.menuReport.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(Main)
        QtCore.QMetaObject.connectSlotsByName(Main)

    def retranslateUi(self, Main):
        Main.setWindowTitle(QtGui.QApplication.translate("Main", "ErgoTime", None, QtGui.QApplication.UnicodeUTF8))
        self.horizontalGroupBox_2.setTitle(QtGui.QApplication.translate("Main", "Current Report", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Main", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Main", "Activity", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Main", "Length", None, QtGui.QApplication.UnicodeUTF8))
        self.dtCurrentStart.setDisplayFormat(QtGui.QApplication.translate("Main", "yyyy-MM-dd HH:mm", None, QtGui.QApplication.UnicodeUTF8))
        self.timeCurrentLen.setDisplayFormat(QtGui.QApplication.translate("Main", "HH:mm:ss", None, QtGui.QApplication.UnicodeUTF8))
        self.btnCurrentStart.setText(QtGui.QApplication.translate("Main", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.btnCurrentStop.setText(QtGui.QApplication.translate("Main", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Main", "Comment", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Main", "Reports", None, QtGui.QApplication.UnicodeUTF8))
        self.btnReportSync.setText(QtGui.QApplication.translate("Main", "Sync", None, QtGui.QApplication.UnicodeUTF8))
        self.chkReportSyncAuto.setText(QtGui.QApplication.translate("Main", "Auto", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSetSelectedDatePrev.setText(QtGui.QApplication.translate("Main", "<", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSetSelectedDateToday.setText(QtGui.QApplication.translate("Main", "Today", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSetSelectedDateNext.setText(QtGui.QApplication.translate("Main", ">", None, QtGui.QApplication.UnicodeUTF8))
        self.reportsWeekday.setText(QtGui.QApplication.translate("Main", "<weekday>", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Main", "Report details", None, QtGui.QApplication.UnicodeUTF8))
        self.btnReportSave.setText(QtGui.QApplication.translate("Main", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.btnReportNew.setText(QtGui.QApplication.translate("Main", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.btnReportRemove.setText(QtGui.QApplication.translate("Main", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.btnReportCancel.setText(QtGui.QApplication.translate("Main", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.timeReportLen.setDisplayFormat(QtGui.QApplication.translate("Main", "HH:mm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Main", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.dtReportStart.setDisplayFormat(QtGui.QApplication.translate("Main", "yyyy-MM-dd HH:mm", None, QtGui.QApplication.UnicodeUTF8))
        self.btnStartHourPlus.setText(QtGui.QApplication.translate("Main", "+H", None, QtGui.QApplication.UnicodeUTF8))
        self.btnStartHourMinus.setText(QtGui.QApplication.translate("Main", "-H", None, QtGui.QApplication.UnicodeUTF8))
        self.btnStartMinutePlus.setText(QtGui.QApplication.translate("Main", "+M", None, QtGui.QApplication.UnicodeUTF8))
        self.btnStartMinuteMinus.setText(QtGui.QApplication.translate("Main", "-M", None, QtGui.QApplication.UnicodeUTF8))
        self.dtReportStop.setDisplayFormat(QtGui.QApplication.translate("Main", "yyyy-MM-dd HH:mm", None, QtGui.QApplication.UnicodeUTF8))
        self.btnStopHourPlus.setText(QtGui.QApplication.translate("Main", "+H", None, QtGui.QApplication.UnicodeUTF8))
        self.btnStopHourMinus.setText(QtGui.QApplication.translate("Main", "-H", None, QtGui.QApplication.UnicodeUTF8))
        self.btnStopMinutePlus.setText(QtGui.QApplication.translate("Main", "+M", None, QtGui.QApplication.UnicodeUTF8))
        self.btnStopMinuteMinus.setText(QtGui.QApplication.translate("Main", "-M", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Main", "Activity", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Main", "Local State", None, QtGui.QApplication.UnicodeUTF8))
        self.lblReportSyncState.setText(QtGui.QApplication.translate("Main", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.lblReportState.setText(QtGui.QApplication.translate("Main", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Main", "Sync state", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Main", "   Length", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Main", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Main", "Comment", None, QtGui.QApplication.UnicodeUTF8))
        self.groupHistory.setTitle(QtGui.QApplication.translate("Main", "History", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("Main", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEdit.setTitle(QtGui.QApplication.translate("Main", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.menuActivity.setTitle(QtGui.QApplication.translate("Main", "Activity", None, QtGui.QApplication.UnicodeUTF8))
        self.menuReport.setTitle(QtGui.QApplication.translate("Main", "Report", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("Main", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("Main", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSettings.setText(QtGui.QApplication.translate("Main", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShortlist.setText(QtGui.QApplication.translate("Main", "Shortlist", None, QtGui.QApplication.UnicodeUTF8))
        self.actionActivitySync.setText(QtGui.QApplication.translate("Main", "Sync", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReportSync.setText(QtGui.QApplication.translate("Main", "Sync", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setText(QtGui.QApplication.translate("Main", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.actionServer_web_page.setText(QtGui.QApplication.translate("Main", "Server web page", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDocumentation.setText(QtGui.QApplication.translate("Main", "Documentation", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("Main", "Exit", None, QtGui.QApplication.UnicodeUTF8))

